inherit_from: .rubocop_todo.yml
require: rubocop-performance

AllCops:
  # note Exclude: overrides, does not merge with, default.
  Exclude:
    - 'bin/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - '.git/**/*'
    - 'solargraph/*'
    - 'db/schema.rb'

Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'
    - 'db/migrate/**/*'
    - 'app/helpers/application_helper.rb'
    - 'app/mailers/application_mailer.rb'
    - 'app/models/application_record.rb'
    - 'config/application.rb'

Layout/IndentationConsistency:
  EnforcedStyle: 'rails'

Style/FrozenStringLiteralComment:
  EnforcedStyle: 'when_needed'

Bundler/OrderedGems:
  TreatCommentsAsGroupSeparators: false

Style/SymbolArray:
  EnforcedStyle: 'brackets'
