require: rubocop-performance

AllCops:
  # note Exclude: overrides, does not merge with, default.
  Exclude:
    - 'bin/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - '.git/**/*'
    - 'solargraph/*'
    - 'db/schema.rb'

# Configuration parameters: AutoCorrect, AllowHeredoc, AllowURI, URISchemes, IgnoreCopDirectives, IgnoredPatterns.
# URISchemes: http, https
Metrics/LineLength:
  Max: 100
  Exclude:
    - 'db/migrate/**/*'
    - 'config/initializers/*'

Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'
    - 'db/migrate/**/*'
    - 'app/helpers/application_helper.rb'
    - 'app/mailers/application_mailer.rb'
    - 'app/models/*.rb'
    - 'config/application.rb'

Layout/IndentationConsistency:
  EnforcedStyle: 'rails'

Bundler/OrderedGems:
  TreatCommentsAsGroupSeparators: false

Style/SymbolArray:
  EnforcedStyle: 'brackets'

Style/FrozenStringLiteralComment:
  EnforcedStyle: 'when_needed'
  Exclude:
    - 'db/migrate/**/*'

Style/HashSyntax:
  Exclude:
    - 'db/migrate/**/*'

Metrics/MethodLength:
  Exclude:
    - 'db/migrate/**/*'

Style/StringLiterals:
  Exclude:
    - 'db/migrate/**/*'

Layout/EmptyLines:
  Exclude:
    - 'db/migrate/**/*'
