version: '2'

services:
  dbhost:
    environment:
      POSTGRES_PASSWORD: stupidpassword
    image: postgres:alpine
    volumes:
      - /home/aflanagan/data/devcamp:/var/lib/postgresql/data
      - ./setup-dbhost:/docker-entrypoint-initdb.d
  website:
    image: devcampportfolio_website
    environment:
      RAILS_ENV: development
      RAILS_LOG_TO_STDOUT: "true"
      RAILS_SERVE_STATIC_FILES: "true" # replace with nginx later
    build:
      context: .
      args:
        appuser: devcampportfolio
        apphome: /home/devcampportfolio/app
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails db:create && bundle exec rails db:migrate && bundle exec rails s -p 3000 -b '0.0.0.0'"
    depends_on:
      - dbhost
    ports:
      - "3000:3000"
    volumes:
      - ./app/:/home/devcampportfolio/app/app
      - ./babel.config.js:/home/devcampportfolio/app/babel.config.js
      - ./bin/:/home/devcampportfolio/app/bin
      - ./.browserslistrc:/home/devcampportfolio/app/.browserslistrc
      - ./config/:/home/devcampportfolio/app/config
      - ./config.ru:/home/devcampportfolio/app/config.ru
      - ./db/:/home/devcampportfolio/app/db
      - ./Gemfile:/home/devcampportfolio/app/Gemfile
      - ./Gemfile.lock:/home/devcampportfolio/app/Gemfile.lock
      - ./jest.config.js:/home/devcampportfolio/app/jest.config.js
      - ./lib/:/home/devcampportfolio/app/lib
      - ./package.json:/home/devcampportfolio/app/package.json
      - ./postcss.config.js:/home/devcampportfolio/app/postcss.config.js
      - ./.ruby-version:/home/devcampportfolio/app/.ruby-version
      - ./yarn.lock:/home/devcampportfolio/app/yarn.lock
