version: '2'

services:
  dbhost:
    environment:
      POSTGRES_PASSWORD: stupidpassword
    image: postgres:alpine
    volumes:
      - /home/aflanagan/data/devcamp:/var/lib/postgresql/data
      - ./setup-dbhost:/docker-entrypoint-initdb.d
  website:
    image: devcampportfolio_website
    environment:
      RAILS_ENV: development
      RAILS_LOG_TO_STDOUT: "true"
      RAILS_SERVE_STATIC_FILES: "true" # replace with nginx later
    build:
      context: .
      args:
        appuser: devcampportfolio
        apphome: /home/devcampportfolio/app
    # command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails db:create && bundle exec rails s -p 3000"
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails db:create && bundle exec rails db:migrate && bundle exec rails s -p 3000 -b '0.0.0.0'"
    depends_on:
      - dbhost
    ports:
      - "3000:3000"
    volumes:
      - ./app:/home/devcampportfolio/app/app
      - ./config:/home/devcampportfolio/app/config
      - ./db:/home/devcampportfolio/app/db
      - ./lib:/home/devcampportfolio/app/lib
      - ./public:/home/devcampportfolio/app/public
    # volumes:
    #   - .:/usr/src/app
