# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  config.vm.box = "centos/7"

  config.vm.provider :libvirt do |libvirt|
    libvirt.nic_model_type = "e1000"
    libvirt.graphics_type = "spice"
  end

  config.vm.provision "file", source: "../config/master.key", destination: "/tmp/master.key"

  config.vm.provision "setup", type: "shell" do |s|
    s.path = "provision.sh"
  end
end
