version: '2'

services:
  dbhost:
    environment:
      POSTGRES_PASSWORD: replaceme
    image: postgres:alpine
    user: postgres
    volumes:
      - /home/devcampportfolio/data:/var/lib/postgresql/data
      - ./setup-dbhost:/docker-entrypoint-initdb.d
  website:
    image: alflanagan/devcampportfolio_website
    environment:
      RAILS_ENV: production
      RAILS_LOG_TO_STDOUT: "true"
      RAILS_SERVE_STATIC_FILES: "true" # replace with nginx later
      PORT: "3000"
      PGHOST: "db"
      PGUSER: "postgres"
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails db:migrate && bundle exec rails s -p 3000 -b '0.0.0.0'"
    depends_on:
      - dbhost
    ports:
      - "80:3000"
